---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: plexpy
    state: absent

- name: Wait for Plex Logs folder to be created by Plex
  wait_for:
    path: "{{mnt.docker_data}}/plex/Library/Application Support/Plex Media Server/Logs"
    state: present

- name: Create plexpy directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "{{mnt.docker_data}}/plexpy"
    
- name: Setup default plexpy docker volume to be merged
  set_fact:
    plexpy_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{mnt.docker_data}}/plexpy:/config"
      - "{{mnt.docker_data}}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro"

- name: Create and start container
  docker_container:
    name: plexpy
    image: shiggins8/tautulli
    pull: yes
    published_ports:
      - "127.0.0.1:8181:8181"
    env:
      ADVANCED_GIT_BRANCH: v2
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VIRTUAL_HOST: "plexpy.{{domain}}"
      VIRTUAL_PORT: 8181
      LETSENCRYPT_HOST: "plexpy.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes: "{{plexpy_volumes + docker_volumes.plexpy|default([])}}"
    restart_policy: always
    networks:
      - name: cloudbox
        aliases:
          - plexpy
    state: started
