---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: znc

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: znc
    state: absent

- name: Setup default sonarr docker volume to be merged
  set_fact:
    znc_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{mnt.docker_data}}/znc:/config"

- name: Create and start container
  docker_container:
    name: znc
    image: "linuxserver/znc"
    published_ports:
      - "{{znc_port}}:{{znc_port}}/tcp"
    volumes: "{{docker_volumes.znc|default([])}} + {{znc_volumes}}"
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.20
        aliases:
          - znc
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    restart_policy: always
    state: started
